version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 15672:15672

  producer:
    image: prashantdave/dotnet-rabbitmq-producer:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Producer/Dockerfile
    depends_on:
      - rabbitmq

  consumer:
    image: prashantdave/dotnet-rabbitmq-consumer:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on:
      - rabbitmq